// const main = async () => {

// };

// main().catch((err)=>{
// console.error(err);
// })

console.log("hello world");